### consulta de autores
GET http://api.publicarlibros/autor

### Adicionar autor
POST http://api.publicarlibros/autor
Content-Type: application/json

{
  "CI": "9000100",
  "nombre": "Mario",
  "apellidos": "Vargas",
  "biografia": "Autor de prueba"
}

### Modificar autor
PUT http://api.publicarlibros/autor/1
Content-Type: application/json

{
  "biografia": "Biografia actualizada"
}

### Eliminar autor
DELETE http://api.publicarlibros/autor/1