### consulta de productos
GET http://api.publicarlibros/productos

### Modificar Productos
PUT http://api.publicarlibros/productos/1

{
    "codBarras":"75010571001",
    "descripcion":"Arroz Integral 3kg",
    "stock":85,
    "precio_unitario":15,
    "creado_por":"2",
    "fecha_registro":"2026-06-12"
}

### Adiccionar
POST http://api.publicarlibros/productos

{
    "codBarras":"75010571001",
    "descripcion":"Arroz Integral 3kg",
    "stock":85,
    "precio_unitario":15,
    "fecha_registro":"2026-06-12"
}

### Eliminar producto
DELETE http://api.publicarlibros/productos/23
