### consulta de usuarios
GET http://api.publicarlibros/users

### consulta de usuario por id
GET http://api.publicarlibros/users/1

### Modificar usuario
PUT http://api.publicarlibros/users/1
Content-Type: application/json

  {
    "username": "maria_personal",
    "email": "maria.personal@example.com",
    "password": 1,
    "rol": "Personal",
    "activo": 1,
    "fecha_registro": "2026-08-26 "
  }

### Adicionar usuario
POST http://api.publicarlibros/users
Content-Type: application/json

{
   "username": "maria_personal",
   "email": "maria.personal@example.com",
   "password": 1,
   "rol": "Personal",
   "activo": 1,
   "fecha_registro": "2026-08-26 "
}


### Eliminar usuario
DELETE http://api.publicarlibros/users/1